### PR TITLE
Add owners files

### LINKED ISSUE #6: Update `CODEOWNERS`

### PR DESCRIPTION
**Pull request by TerryHowe**
Closes #6

### CODE REVIEW

**Review by SteveLasker — COMMENTED** [review]
Thanks @TerryHowe,
Is this PR to acknowledge the current state, or to nominate folks? Just seems we might want some more non-microsoft folks here. Would you want to represent as well?

**Comment by TerryHowe** [comment]
> Thanks @TerryHowe, Is this PR to acknowledge the current state, or to nominate folks? Just seems we might want some more non-microsoft folks here. Would you want to represent as well?

I just copied the owners files from oras-go.

**Comment by TerryHowe** [comment]
I can represent for this project. I don't see anything in the governance about ownership percentage on sub projects though.

**Review by sajayantony — CHANGES_REQUESTED** [review]
Can we just start with @shizhMSFT @TerryHowe and @Wwwsylvia only as code owners.

**Comment by SteveLasker** [comment]
Thanks @TerryHowe,
 
 >  I don't see anything in the governance about ownership percentage on sub projects though.
 
 You're correct, I don't believe we ever called that out specifically. There are a few things we've been doing for the general health of the project that we should likely write down. That said, I would approve you as a maintainer of the sub-project. 
 
 To @sajayantony's point, I'm also fine with @shizhMSFT, @TerryHowe and @Wwwsylvia as owners.  I personally don't need any additional sub-project ownership here.

**Comment by shizhMSFT** [comment]
I've created PR #16 to include Terry, Sylvia, and myself as the maintainers. BTW, we are using `MAINTAINERS.md` (`Maintainer` role) instead of `OWNERS.md` (`Admin` role).

**Comment by SteveLasker** [comment]
@shizhMSFT do we have the use of maintainers and owners files documented in the governance? This is fairly new addition. Good, just not documented.

**Comment by shizhMSFT** [comment]
> @shizhMSFT do we have the use of maintainers and owners files documented in the governance? This is fairly new addition. Good, just not documented.

In fact, in the governance, we always use the term _maintainers_ but maintainers are treated as `Admin`s in all existing repositories. To minimize the impact, new maintainers are onboarded as maintainers instead of owners. But indeed, we need to document it clearly in the governance.

/cc @FeynmanZhou @yizha1

**Review by SteveLasker — COMMENTED** [review]
Thanks @shizhMSFT for the updates and welcome @TerryHowe as a maintainer.
I captured the need to document MAINTAINERS and OWNERS in https://github.com/oras-project/community/issues/47

Before I LGTM, the notary repos were following a convention of declaring the Org Maintainers as well: [notation/MAINTAINERS](https://github.com/notaryproject/notation/blob/main/MAINTAINERS) and [notation/CODEOWNERS](https://github.com/notaryproject/notation/blob/main/CODEOWNERS)

What convention should we follow in ORAS?

**Comment by shizhMSFT** [comment]
> What convention should we follow in ORAS?

Each repository has its own context and org-level maintainers have limited resources to maintain them. That's why we have sub-project level maintainers. We should not include org-level maintainers in the maintainers file of individual repos except the `community` repo unless specific org-level maintainers want to be repo-level maintainers.

With the same reason, org-level maintainers should not be added to the `CODEOWNERS` file. Otherwise, org-level maintainers are required to review all PRs in all repos, which is not feasible for our oras project.

**Comment by SteveLasker** [comment]
@shizhMSFT, this makes sense. We just need to include that logic in the governance, as it wasn’t obvious why org maintainers were included in some vs the others.

**Pull request closed without merging**
